sonar.projectKey=Ezra12363_smart-maintenance
sonar.organization=default # ou votre org
sonar.projectName=SmartMaintenance Spaghetti
sonar.sources=src
sonar.exclusions=node_modules/**,coverage/**
sonar.tests=tests
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarcloud.io
